import {beforeEach,afterEach,it,expect,vi} from 'vitest';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {assessTrustedStorePage,registerTrustedStore,runTrustedStoreApprovals} from '../src/trusted-stores';
import {dashboardListingReview} from '../src/index';
import {trustedStoreOperations} from '../src/trusted-store-operations';
import type {Env} from '../src/types';
let db:DatabaseSync,env:Env;
function adapter(){
  const prepare=(sql:string)=>{
    let values:unknown[]=[];
    return {bind(...args:unknown[]){values=args;return this;},async first(){return db.prepare(sql).get(...values as never[])??null;},
      async all(){return {results:db.prepare(sql).all(...values as never[]),success:true};},
      execute(){const result=db.prepare(sql).run(...values as never[]);return {success:true,meta:{changes:Number(result.changes),last_row_id:Number(result.lastInsertRowid)}};},async run(){return this.execute();}};
  };
  return {prepare,async batch(statements:Array<{execute:()=>unknown}>){db.exec('BEGIN');try{const out=[];for(const statement of statements)out.push(statement.execute());db.exec('COMMIT');return out;}catch(error){db.exec('ROLLBACK');throw error;}}};
}

beforeEach(()=>{db=new DatabaseSync(':memory:');for(const n of readdirSync('migrations').filter(n=>n.endsWith('.sql')).sort())db.exec(readFileSync('migrations/'+n,'utf8'));env={SPAWN_DB:adapter(),TRUSTED_STORE_AUTO_APPROVAL_ENABLED:'true',BOARD_ACCESS_TOKEN:'test'} as unknown as Env;vi.stubGlobal('fetch',vi.fn(async()=>{throw new Error('Unexpected network');}));});
afterEach(()=>{db.close();vi.unstubAllGlobals();});
const id='a'.repeat(64),title='Delta Reign Elite Trainer Box',normal='https://cards.example/product',amazon='https://www.amazon.com.mx/dp/B0H27L3TKW';
function page(url=normal,seller:unknown=url===amazon?{identifier:'SELLER1'}:{},shipping=true){return '<title>Amazon product B0H27L3TKW</title><script type="application/ld+json">'+JSON.stringify({'@type':'Product',url,name:title,offers:{'@type':'Offer',url,availability:'https://schema.org/InStock',price:'1000',priceCurrency:'MXN',seller,shippingDetails:shipping?{shippingOrigin:{addressCountry:'MX'},shippingDestination:{addressCountry:'MX'}}:null}})+'</script>';}
function candidate(url=normal){const now=new Date().toISOString();db.prepare("INSERT INTO inventory(listing_key,canonical_url,retailer,title,watch_category,first_seen_at,last_seen_at,status,language) VALUES('listing',?,'Store',?,'delta_reign',?,?,'unknown','unknown')").run(url,title,now,now);db.prepare("INSERT INTO monitoring_candidates(candidate_id,source,source_url,source_listing_key,vendor,vendor_key,product_name,product_family,print_series,language,discovered_at,review_eligible) VALUES(?,'scan',?,'listing','Store','store',?,'pokemon_tcg','Delta Reign','unknown',?,1)").run(id,url,title,now);return {...db.prepare('SELECT * FROM monitoring_candidates').get(),watch_category:'delta_reign'};}
function trust(url=normal,sellerKey='store:https://cards.example'){db.prepare("INSERT INTO trusted_store_rules(id,origin,seller_key,category,source_candidate_id,created_by,created_at) VALUES('rule',?,?,'delta_reign','source','admin',?)").run(new URL(url).origin,sellerKey,'2000-01-01T00:00:00.000Z');}
const fetchPage=(html=page())=>vi.fn(async()=>new Response(html));
async function publish(candidateId:string,form:FormData,actor:string){const url=new URL('https://spawn.test/dashboard/listing/'+candidateId);return (await dashboardListingReview(new Request(url,{method:'POST'}),url,env,{form,actor}))?.status===303;}
it('publishes an eligible store listing once and retains its proof and unseen admin flag',async()=>{candidate();trust();const f=fetchPage();await runTrustedStoreApprovals(env,publish,f);await runTrustedStoreApprovals(env,publish,f);expect(db.prepare('SELECT status,reviewed_by FROM monitoring_candidates').get()).toMatchObject({status:'ACCEPTED',reviewed_by:'auto:trusted-store:rule'});expect(db.prepare('SELECT COUNT(*) n FROM customer_inventory_events').get()?.n).toBe(1);expect(db.prepare('SELECT outcome,admin_seen_at,details_json FROM trusted_store_attempts').get()).toMatchObject({outcome:'AUTO_APPROVED',admin_seen_at:null,details_json:expect.stringContaining('exact-product-jsonld-v1')});expect(f).toHaveBeenCalledTimes(1);});
it.each(['disabled','revoked','rejected','wrong-category','suppressed'])('never publishes when %s',async condition=>{candidate();trust();if(condition==='disabled')env.TRUSTED_STORE_AUTO_APPROVAL_ENABLED='false';if(condition==='revoked')db.exec('UPDATE trusted_store_rules SET enabled=0');if(condition==='rejected')db.exec("UPDATE monitoring_candidates SET status='REJECTED'");if(condition==='wrong-category')db.exec("UPDATE trusted_store_rules SET category='ascended_heroes'");if(condition==='suppressed')db.exec("INSERT INTO vendors(vendor_key,vendor_name,status,updated_at,reason) VALUES('store','Store','SUPPRESSED','now','test')");const p=vi.fn();await runTrustedStoreApprovals(env,p,fetchPage());expect(p).not.toHaveBeenCalled();});
it.each([{}, {name:'SELLER1'}, {identifier:{}}, {'@id':'#seller'}, {url:'https://www.amazon.com.mx/'}, {url:amazon}, {identifier:'DIFFERENT'}])('does not inherit marketplace approval across missing or changed seller IDs: %j',async seller=>{candidate(amazon);trust(amazon,'seller:SELLER1');const now=new Date().toISOString();db.prepare("INSERT INTO amazon_watchlist(asin,product_name,product_url,watch_category,language,source,first_discovered_at,last_discovered_at,updated_at) VALUES('B0H27L3TKW',?,?,'delta_reign','english','test',?,?,?)").run(title,amazon,now,now,now);const p=vi.fn();await runTrustedStoreApprovals(env,p,fetchPage(page(amazon,seller)));expect(p).not.toHaveBeenCalled();});
it('enrolls a verified Amazon product in Catch and publishes Spawn visibility with no initial buyable alert',async()=>{candidate(amazon);trust(amazon,'seller:SELLER1');const now=new Date().toISOString();db.prepare("INSERT INTO amazon_watchlist(asin,product_name,product_url,watch_category,language,source,first_discovered_at,last_discovered_at,updated_at) VALUES('B0H27L3TKW',?,?,'delta_reign','spanish','test',?,?,?)").run(title,amazon,now,now,now);await runTrustedStoreApprovals(env,publish,fetchPage(page(amazon)));expect(db.prepare("SELECT lifecycle_status,poll_interval_minutes,alert_on_initial_buyable FROM amazon_watchlist WHERE asin='B0H27L3TKW'").get()).toMatchObject({lifecycle_status:'PUBLISHED',poll_interval_minutes:60,alert_on_initial_buyable:0});expect(db.prepare('SELECT status FROM monitoring_candidates').get()?.status).toBe('ACCEPTED');});
it('does not turn missing shipping evidence or a blocked page into approval',async()=>{candidate();trust();const p=vi.fn(),f=fetchPage(page(normal,{},false));await runTrustedStoreApprovals(env,p,f);await runTrustedStoreApprovals(env,p,f);expect(p).not.toHaveBeenCalled();expect(f).toHaveBeenCalledTimes(1);expect(assessTrustedStorePage('<title>Robot check</title>'+page(),normal,title,null)).toBeNull();});
it('rejects mismatching identities, unrelated hosts and malformed product metadata',()=>{expect(assessTrustedStorePage(page(),normal,'Another product',null)).toBeNull();expect(assessTrustedStorePage(page(),normal,'Delta Reign Elite Trainer Box','MISSING')).toBeNull();expect(assessTrustedStorePage(page(),normal+'.evil',title,null)).toBeNull();expect(assessTrustedStorePage(page().replace(normal,'https://['),normal,title,null)).toBeNull();});
it('registers trust only from a selected human approval and records an unprovable request',async()=>{const c=candidate();const form=new FormData();form.set('trust_store','on');form.set('fulfilment_region_state','DOMESTIC');await registerTrustedStore(env,c,form,'admin',fetchPage());expect(db.prepare('SELECT created_by,source_candidate_id FROM trusted_store_rules').get()).toMatchObject({created_by:'admin',source_candidate_id:id});db.exec('DELETE FROM trusted_store_rules');await registerTrustedStore(env,c,form,'auto:trusted-store:rule',fetchPage());expect(db.prepare('SELECT COUNT(*) n FROM trusted_store_rules').get()?.n).toBe(0);await registerTrustedStore(env,c,form,'admin',fetchPage('not a product'));expect(db.prepare('SELECT outcome FROM trusted_store_attempts').get()?.outcome).toBe('TRUST_NOT_CREATED');});
it('retains an interrupted publication flag and releases locks after errors',async()=>{candidate();trust();await runTrustedStoreApprovals(env,async()=>{throw new Error('Publication failed');},fetchPage());expect(db.prepare('SELECT outcome,admin_seen_at FROM trusted_store_attempts').get()).toMatchObject({outcome:'ERROR',admin_seen_at:null});expect(db.prepare('SELECT COUNT(*) n FROM ops_review_locks').get()?.n).toBe(0);});
it('allows administrators to acknowledge flags and revoke trust, while viewers cannot mutate it',async()=>{candidate();trust();await runTrustedStoreApprovals(env,publish,fetchPage());const operator={email:'admin',subject:'admin',role:'admin' as const};const request=(action:string,ruleId='rule')=>new Request('https://spawn.test/ops/trusted-stores',{method:'POST',body:new URLSearchParams({action,id:ruleId})});expect((await trustedStoreOperations(request('revoke'),env,{...operator,role:'viewer'})).status).toBe(403);await trustedStoreOperations(request('revoke'),env,operator);expect(db.prepare('SELECT enabled,revoked_by FROM trusted_store_rules').get()).toMatchObject({enabled:0,revoked_by:'admin'});const event=db.prepare('SELECT id FROM trusted_store_attempts').get()!;await trustedStoreOperations(request('seen',String(event.id)),env,operator);expect(db.prepare('SELECT admin_seen_by FROM trusted_store_attempts').get()?.admin_seen_by).toBe('admin');});

it.each(['publish','reject'])('accepts an empty %s comment without weakening delivery gates or authentication',async action=>{candidate();const url=new URL('https://spawn.test/dashboard/listing/'+id),form=new FormData();form.set('action',action);form.set('disposition','visibility_only');expect((await dashboardListingReview(new Request(url,{method:'POST',body:form}),url,env))?.status).toBe(404);if(action==='publish')expect((await dashboardListingReview(new Request(url,{method:'POST'}),url,env,{form,actor:'admin'}))?.status).toBe(400);form.set('fulfilment_region_state','DOMESTIC');form.set('retailer_country','MX');form.set('ship_from_country','MX');expect((await dashboardListingReview(new Request(url,{method:'POST'}),url,env,{form,actor:'admin'}))?.status).toBe(303);expect(db.prepare('SELECT reason,decided_by FROM listing_publication_decisions WHERE candidate_id=?').get(id)).toMatchObject({reason:expect.stringContaining('No optional comment provided'),decided_by:'admin'});});
it('leaves historical pending listings outside a newly created trust rule',async()=>{candidate();trust();db.prepare('UPDATE trusted_store_rules SET created_at=?').run(new Date(Date.now()+1000).toISOString());const p=vi.fn();await runTrustedStoreApprovals(env,p,fetchPage());expect(p).not.toHaveBeenCalled();});
it('rechecks revocation after fetching and respects an administrator review lock',async()=>{candidate();trust();const p=vi.fn();db.prepare('INSERT INTO ops_review_locks VALUES(?,?,?)').run('/dashboard/listing/'+id,'admin',Date.now()+60000);const f=fetchPage();await runTrustedStoreApprovals(env,p,f);expect(f).not.toHaveBeenCalled();db.exec('DELETE FROM ops_review_locks');await runTrustedStoreApprovals(env,p,async()=>{db.exec('UPDATE trusted_store_rules SET enabled=0');return new Response(page());});expect(p).not.toHaveBeenCalled();});
it.each(['REJECTED','APPROVED','PUBLISHED'])('does not reverify an Amazon target in state %s',async state=>{candidate(amazon);trust(amazon,'seller:SELLER1');const now=new Date().toISOString();db.prepare("INSERT INTO amazon_watchlist(asin,product_name,product_url,watch_category,language,source,lifecycle_status,first_discovered_at,last_discovered_at,updated_at,canonical_product_id,routing_key,approved_by,approved_at) VALUES('B0H27L3TKW',?,?,'delta_reign','spanish','test',?,?,?,?,'fixture-es-id','delta-reign','admin','2000-01-01T00:00:00Z')").run(title,amazon,state,now,now,now);const f=fetchPage(page(amazon));await runTrustedStoreApprovals(env,vi.fn(),f);expect(f).not.toHaveBeenCalled();expect(db.prepare("SELECT lifecycle_status FROM amazon_watchlist WHERE asin='B0H27L3TKW'").get()?.lifecycle_status).toBe(state);});
it('escapes audit content in the admin page',async()=>{candidate();trust();db.prepare("INSERT INTO trusted_store_attempts(id,candidate_id,attempted_at,outcome,details_json) VALUES('flag',?,'now','ERROR',?)").run(id,'<script>alert(1)</script>');const page=await trustedStoreOperations(new Request('https://spawn.test/ops/trusted-stores'),env,{email:'admin',subject:'admin',role:'admin'});expect(await page.text()).toContain('&lt;script&gt;alert(1)&lt;/script&gt;');});
