import assert from 'node:assert/strict';
import {diagnostic,errorCategory,healthSummary} from './diagnostics.js';
const storage={};
globalThis.chrome={storage:{local:{get:async()=>structuredClone(storage),set:async data=>Object.assign(storage,data)}}};
await Promise.all(Array.from({length:520},(_,index)=>diagnostic('TEST',{index})));
assert.equal(storage.diagnostics.length,500);
assert.equal(storage.diagnostics[0].index,519);
assert.equal(storage.diagnostics[499].index,20);
assert.equal(errorCategory(new Error('secret credential must never appear')),'API_OR_RUNTIME_ERROR');
assert.equal(errorCategory(new Error('Page reload timed out')),'TIMEOUT');
assert.equal(errorCategory(new Error('No tab with id 1')),'TAB_CLOSED');
assert.equal(errorCategory('Intake HTTP 401'),'Intake HTTP 401');
const now=Date.now(),recent={enabled:true,nextAt:now+300000,lastRun:{completedAt:new Date(now-30000).toISOString()}};
assert.match(healthSummary(recent,now),/Recent complete pass/);
assert.match(healthSummary({...recent,activeRun:{at:new Date(now-300001).toISOString(),phase:'reading_batch'}},now),/Interrupted or stalled/);
assert.match(healthSummary({...recent,lastRun:null},now),/Monitoring stale/);
assert.match(healthSummary({...recent,nextAt:null},now),/Schedule missing/);
assert.match(healthSummary({...recent,nextAt:now-120000},now),/overdue/);
chrome.storage.local.set=async()=>{throw new Error('quota');};
await diagnostic('FAILURE');
chrome.storage.local.set=async data=>Object.assign(storage,data);
await diagnostic('RECOVERED');
assert.equal(storage.diagnostics[0].type,'RECOVERED');
console.log('Diagnostics passed: concurrent logging, bounded retention, error redaction, stale/overdue/interrupted health and storage failure recovery.');
