import type {CustomerEnv} from './customer';
import {termsCopy} from './customer-terms-copy';
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
export function legalReady(env:CustomerEnv){return env.CUSTOMER_LEGAL_PUBLISHED==='true'&&Boolean(env.CUSTOMER_OPERATOR_NAME?.trim()&&env.CUSTOMER_OPERATOR_ADDRESS?.trim()&&env.CUSTOMER_PRIVACY_EMAIL?.includes('@')&&env.CUSTOMER_TERMS_VERSION&&env.CUSTOMER_TERMS_EFFECTIVE_DATE);}
export function customerLegal(env:CustomerEnv,privacy=false){
 if(!legalReady(env))return '<h1>Terms are being prepared</h1><p>Membership onboarding is not open yet. Please check back shortly.</p>';
 const operator=`<p><strong>Responsable:</strong> ${esc(env.CUSTOMER_OPERATOR_NAME!)}<br><strong>Domicilio:</strong> ${esc(env.CUSTOMER_OPERATOR_ADDRESS!)}<br><strong>Contacto:</strong> ${esc(env.CUSTOMER_PRIVACY_EMAIL!)}<br><strong>Versión:</strong> ${esc(env.CUSTOMER_TERMS_VERSION!)} · ${esc(env.CUSTOMER_TERMS_EFFECTIVE_DATE!)}</p>`;
 if(!privacy){const text=termsCopy.replaceAll('[correo]',env.CUSTOMER_PRIVACY_EMAIL!).replaceAll('[canal de soporte]','la página de soporte en /app/support').replaceAll('[URL pública del aviso integral]','/privacy');return `<h1>Términos de uso</h1>${operator}${text.split(/\r?\n\r?\n/).map(p=>p.startsWith('## ')?`<h2>${esc(p.slice(3))}</h2>`:`<p>${esc(p.replace(/\r?\n/g,' '))}</p>`).join('')}<p><a href="/privacy">Aviso de privacidad integral</a></p>`;}
 return `<h1>Aviso de privacidad integral</h1>${operator}
 <h2>Datos y finalidades</h2><p>Tratamos correo verificado, identificador de cuenta, identificador de Discord, pertenencia y roles en el servidor Garfield, fechas de validación, aceptación de términos, declaración de mayoría de edad, cambios de acceso y solicitudes de soporte. No solicitamos documentos de identidad ni datos de pago en este piloto gratuito.</p><p>Usamos estos datos para autenticarte, verificar tu membresía, dar acceso al inventario, sincronizar el rol de acceso, atender soporte, prevenir abuso y documentar decisiones. El identificador de cuenta y la fecha aparecen como marca en la vista de inventario. No impide capturas.</p>
 <h2>Proveedores y comunicaciones</h2><p>Cloudflare aloja la plataforma y procesa el acceso por correo. Discord permite comprobar membresía y gestionar roles. Las solicitudes de soporte y el identificador de cuenta se comparten con el equipo autorizado en un canal privado de Discord; el correo es visible para administradores autorizados. Estos servicios pueden procesar información fuera de México. No retenemos tokens OAuth de usuario después de vincular la cuenta.</p><p>No usamos tu pertenencia al servidor como autorización para publicidad o mensajes directos promocionales. Las finalidades promocionales futuras requerirán una elección separada y opcional. No vendemos tus datos.</p>
 <h2>Acceso, corrección, cancelación y oposición</h2><p>Para ejercer derechos ARCO, revocar un consentimiento o limitar uso/divulgación, escribe a ${esc(env.CUSTOMER_PRIVACY_EMAIL!)} o abre una solicitud en <a href="/app/support">soporte</a>. Indica el derecho que deseas ejercer, los datos relevantes y un medio de respuesta. Verificaremos tu identidad por un medio proporcionado al caso y te explicaremos el trámite y los plazos aplicables. No envíes contraseñas ni códigos.</p>
 <h2>Conservación y cambios</h2><p>Conservamos los datos necesarios mientras la cuenta está activa. Al solicitar cierre revisamos qué datos pueden eliminarse y qué registros deben conservarse por obligaciones o reclamaciones; comunicaremos el resultado. No prometemos borrado inmediato ni conservación indefinida. Las copias de soporte en Discord también forman parte de la revisión.</p><p>Las cookies de autenticación son necesarias para el acceso. Esta aplicación no añade cookies publicitarias. Publicamos aquí la versión vigente del aviso y comunicaremos cambios materiales en la plataforma antes de aplicarlos. Los términos de uso no sustituyen consentimientos específicos exigibles.</p>`;
}
