import type {PageEvidence} from './product-page-evidence';
export interface RefreshRecord extends PageEvidence {id:string;canonical_url:string;last_seen_at:string;startedAt:string;finishedAt:string;httpStatus:number;htmlHash:string}
const q=(v:unknown)=>v==null?'NULL':typeof v==='number'?String(v):`'${String(v).replace(/'/g,"''")}'`;
export function refreshStatements(row:RefreshRecord,runId:string,eligibleCte:string,now=new Date()):string[]{
 if(!/^[a-zA-Z0-9_-]{1,100}$/.test(row.id)||!['AVAILABLE','SOLD_OUT','UNKNOWN','BLOCKED','ERROR'].includes(row.outcome)||!Number.isFinite(Date.parse(row.finishedAt))||Date.parse(row.finishedAt)>now.getTime()||Date.parse(row.finishedAt)<now.getTime()-30*60_000||Date.parse(row.startedAt)>Date.parse(row.finishedAt)||!(row.priceMxn==null||(Number.isFinite(row.priceMxn)&&row.priceMxn>0)))throw Error('Invalid or expired refresh evidence');
 const attempt=`customer-refresh:${runId}:${row.id}`,ok=['AVAILABLE','SOLD_OUT'].includes(row.outcome),state=row.outcome==='AVAILABLE'?'ACTIVE':row.outcome==='ERROR'?'STALE':row.outcome;
 const due=new Date(Date.parse(row.finishedAt)+(ok?24:6)*3600000).toISOString();
 const evidence=JSON.stringify({run:runId,html_sha256:row.htmlHash,assessment:row.evidence});
 const unchanged=`listing_key=${q(row.id)} AND canonical_url=${q(row.canonical_url)} AND last_seen_at=${q(row.last_seen_at)} AND COALESCE(pricing_observed_at,'')<=${q(row.startedAt)} AND COALESCE(availability_observed_at,'')<=${q(row.startedAt)} AND listing_key IN (SELECT id FROM eligible)`;
 const sql=[`${eligibleCte} INSERT OR IGNORE INTO inventory_revalidation_attempts(attempt_id,listing_key,domain,started_at,finished_at,outcome,http_status,parser_version,observed_price_mxn,evidence) SELECT ${[attempt,row.id,new URL(row.canonical_url).hostname,row.startedAt,row.finishedAt,row.outcome,row.httpStatus,'exact-product-jsonld-v1',row.priceMxn,evidence].map(q).join(',')} FROM inventory WHERE ${unchanged};`];
 if(ok)sql.push(`${eligibleCte} UPDATE inventory SET status=${q(row.outcome==='AVAILABLE'?'available':'sold_out')},availability_state=${q(row.outcome==='AVAILABLE'?'available':'sold_out')},last_seen_at=${q(row.finishedAt)},availability_observed_at=${q(row.finishedAt)},availability_freshness_status='REVALIDATED',price_mxn=COALESCE(${q(row.priceMxn)},price_mxn),price_verification_status=${q(row.priceMxn==null?'PENDING':'VERIFIED')},pricing_observed_at=CASE WHEN ${q(row.priceMxn)} IS NOT NULL THEN ${q(row.finishedAt)} ELSE pricing_observed_at END WHERE ${unchanged} AND EXISTS(SELECT 1 FROM inventory_revalidation_attempts WHERE attempt_id=${q(attempt)});`);
 sql.push(`${eligibleCte} INSERT INTO inventory_revalidation_state(listing_key,lifecycle_state,due_at,last_attempt_at,last_success_at,last_outcome,next_eligible_at,consecutive_failures,evidence_revision,updated_at)
 SELECT ${[row.id,state,due,row.finishedAt,ok?row.finishedAt:null,row.outcome,due,ok?0:1,1,row.finishedAt].map(q).join(',')} FROM inventory WHERE listing_key=${q(row.id)} AND listing_key IN (SELECT id FROM eligible) AND last_seen_at=${q(ok?row.finishedAt:row.last_seen_at)} AND EXISTS(SELECT 1 FROM inventory_revalidation_attempts WHERE attempt_id=${q(attempt)})
 ON CONFLICT(listing_key) DO UPDATE SET lifecycle_state=excluded.lifecycle_state,due_at=excluded.due_at,last_attempt_at=excluded.last_attempt_at,last_success_at=COALESCE(excluded.last_success_at,inventory_revalidation_state.last_success_at),last_outcome=excluded.last_outcome,next_eligible_at=excluded.next_eligible_at,consecutive_failures=CASE WHEN ${ok?1:0} THEN 0 ELSE inventory_revalidation_state.consecutive_failures+1 END,evidence_revision=inventory_revalidation_state.evidence_revision+1,updated_at=excluded.updated_at WHERE COALESCE(inventory_revalidation_state.last_attempt_at,'')<excluded.last_attempt_at AND inventory_revalidation_state.lifecycle_state!='ARCHIVED';`);
 return sql;
}
