import type { Env } from "./types";

export async function dashboardData(env: Env) {
  const [lastSuccess,recent,inventory,vendors,candidates,feedback,verificationQueue,catalogVersion,listingQueue,publicationVersion,publishedCatalog,pricingCatalog,seedCampaigns,revalidation,removalReviews,customerEvents] = await Promise.all([
    env.SPAWN_DB.prepare("SELECT value,updated_at FROM worker_state WHERE key='last_success'").first(),
    env.SPAWN_DB.prepare("SELECT started_at,finished_at,status,error FROM scan_runs ORDER BY started_at DESC LIMIT 8").all(),
    env.SPAWN_DB.prepare("SELECT COUNT(*) total,SUM(status='available') available,SUM(status='unknown') unknown,SUM(availability_state='preorder_placeholder') placeholders,MAX(last_seen_at) freshest FROM inventory").first(),
    env.SPAWN_DB.prepare("SELECT status,COUNT(*) count FROM vendors GROUP BY status").all(),
    env.SPAWN_DB.prepare("SELECT status,print_series,COUNT(*) count FROM monitoring_candidates GROUP BY status,print_series").all(),
    env.SPAWN_DB.prepare("SELECT week_key,COUNT(*) responses,ROUND(AVG(usefulness),1) usefulness,SUM(successful_purchase) purchases FROM weekly_feedback_responses GROUP BY week_key ORDER BY week_key DESC LIMIT 8").all(),
    env.SPAWN_DB.prepare(`SELECT w.asin,w.product_name,w.product_url,w.watch_category,w.language,w.lifecycle_status,w.first_discovered_at,w.last_discovered_at,w.verification_attempt_id,w.evidence_revision,w.lane,COALESCE(w.routing_key_v2,w.routing_key) routing_key,w.alert_on_initial_buyable,w.staging_enabled,w.staged_at,
      a.completed_at verification_completed_at,a.outcome verification_outcome,a.access_outcome,a.http_status,a.canonical_product_id,a.observed_availability,a.gate_results_json,a.confidence,a.unresolved_questions,n.status approval_notice_status,n.attempts approval_notice_attempts,n.last_error approval_notice_error,
      (SELECT json_group_array(json_object('decision',d.decision,'reason',d.reason,'actor',d.decided_by,'decided_at',d.decided_at,'catalog_version',d.resulting_catalog_version)) FROM amazon_catalog_decisions d WHERE d.asin=w.asin) decision_history
      FROM amazon_watchlist w LEFT JOIN amazon_verification_attempts a ON a.id=w.verification_attempt_id LEFT JOIN approval_notifications n ON n.evidence_revision=w.evidence_revision
      WHERE w.lifecycle_status!='PUBLISHED' ORDER BY w.first_discovered_at ASC LIMIT 200`).all(),
    env.SPAWN_DB.prepare("SELECT value,updated_at FROM worker_state WHERE key='amazon_catalog_version'").first(),
    env.SPAWN_DB.prepare(`SELECT c.candidate_id,c.source_url,c.vendor,c.product_name,c.product_family,c.print_series,c.product_type,c.language,c.retailer_sku,c.observed_price_mxn,c.availability_state,c.discovered_at,n.status notification_status,n.attempts notification_attempts,n.last_error notification_error FROM monitoring_candidates c LEFT JOIN discovery_approval_notifications n ON n.candidate_id=c.candidate_id WHERE c.review_eligible=1 AND c.status='PENDING' ORDER BY c.discovered_at ASC LIMIT 200`).all(),
    env.SPAWN_DB.prepare("SELECT value,updated_at FROM worker_state WHERE key='listing_publication_version'").first(),
    env.SPAWN_DB.prepare("SELECT asin,product_name,lane,poll_interval_minutes,updated_at FROM amazon_watchlist WHERE lifecycle_status='PUBLISHED' ORDER BY product_name,asin").all(),
    env.SPAWN_DB.prepare(`SELECT p.id,p.canonical_name,p.amazon_launch_mxn,p.amazon_confidence,p.amazon_source_url,p.amazon_captured_at,p.collectr_usd,p.collectr_source_url,p.collectr_captured_at,p.usd_mxn_rate,COUNT(i.listing_key) mapped_offers FROM products p LEFT JOIN inventory i ON i.product_id=p.id GROUP BY p.id ORDER BY p.canonical_name`).all(),
    env.SPAWN_DB.prepare("SELECT campaign_id,source,received_at,item_count,accepted_count,duplicate_count,rejected_count FROM seed_campaigns ORDER BY received_at DESC LIMIT 10").all(),
    env.SPAWN_DB.prepare("SELECT lifecycle_state,last_outcome,COUNT(*) count,SUM(datetime(next_eligible_at)<=CURRENT_TIMESTAMP) due FROM inventory_revalidation_state GROUP BY lifecycle_state,last_outcome ORDER BY lifecycle_state,last_outcome").all(),
    env.SPAWN_DB.prepare("SELECT status,COUNT(*) count FROM inventory_removal_reviews GROUP BY status").all(),
    env.SPAWN_DB.prepare("SELECT delivery_status,event_type,COUNT(*) count FROM customer_inventory_events GROUP BY delivery_status,event_type").all()
  ]);
  let catchHealth:unknown=null;
  if(env.CATCH_MONITOR_ENDPOINT) try { const response=await fetch(env.CATCH_MONITOR_ENDPOINT,{headers:{accept:"application/json"}}); catchHealth=response.ok?await response.json():{ok:false,status:response.status}; } catch { catchHealth={ok:false,error:"unreachable"}; }
  return {generated_at:new Date().toISOString(),spawn:{last_success:lastSuccess,recent_runs:recent.results,inventory},vendors:vendors.results,discovery_ingestion:candidates.results,weekly_feedback:feedback.results,verification_queue:verificationQueue.results,catalog_version:catalogVersion,listing_queue:listingQueue.results,publication_version:publicationVersion,published_catalog:publishedCatalog.results,pricing_catalog:pricingCatalog.results,seed_campaigns:seedCampaigns.results,revalidation:revalidation.results,removal_reviews:removalReviews.results,customer_events:customerEvents.results,catch_em_all:catchHealth};
}

const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"})[c]!);
export function renderDashboard(data:Awaited<ReturnType<typeof dashboardData>>, token:string, feedback?:{notice?:string|null;error?:string|null}) {
  const catchData=(data.catch_em_all&&typeof data.catch_em_all==="object"?data.catch_em_all:{}) as Record<string,unknown>;
  const catchRows=Array.isArray(catchData.rows)?catchData.rows as Array<Record<string,unknown>>:[];
  const catchByAsin=new Map(catchRows.map(row=>[String(row.asin||"").toUpperCase(),row]));
  const published=Array.isArray(data.published_catalog)?data.published_catalog as Array<Record<string,unknown>>:[];
  const trackedCount=published.filter(row=>catchByAsin.has(String(row.asin||"").toUpperCase())).length;
  const trackingCoverage=published.map(row=>{const catchRow=catchByAsin.get(String(row.asin||"").toUpperCase());return `<tr><td>${esc(row.product_name)}</td><td><code>${esc(row.asin)}</code></td><td>${catchRow?"✅ Tracked":"⚠️ Not confirmed"}</td><td>${esc(catchRow?.cadenceClass??"—")}</td><td>${esc(catchRow?.cadenceMinutes??"—")}${catchRow?.cadenceMinutes?" min":""}</td><td>${esc(catchRow?.lastAttemptAt??"Never")}</td></tr>`;}).join("");
  const coverageSection=`<section><h2>Catch tracking coverage</h2><p><b>${trackedCount}/${published.length}</b> published Amazon ASINs confirmed in Catch. Pending approval items are not tracked until publication.</p><div class="table"><table><thead><tr><th>Product</th><th>ASIN</th><th>Catch</th><th>Class</th><th>Effective cadence</th><th>Last attempt</th></tr></thead><tbody>${trackingCoverage}</tbody></table></div></section>`;
  const pricing=Array.isArray(data.pricing_catalog)?data.pricing_catalog as Array<Record<string,unknown>>:[],amazonReferenceCount=pricing.filter(row=>row.amazon_launch_mxn!=null&&row.amazon_source_url&&row.amazon_captured_at).length,collectrReferenceCount=pricing.filter(row=>row.collectr_usd!=null&&row.collectr_source_url&&row.collectr_captured_at&&row.usd_mxn_rate!=null).length;
  const localTime=(value:unknown)=>typeof value==="string"&&value?new Date(value).toISOString().slice(0,16):"";
  const pricingRows=pricing.map(row=>{const action=`/dashboard/pricing/${esc(row.id)}?access=${encodeURIComponent(token)}`;return `<tr><td>${esc(row.canonical_name)}</td><td>${esc(row.mapped_offers)}</td><td>${row.amazon_launch_mxn==null?"⚠️ Missing":`MX$${esc(row.amazon_launch_mxn)} · ${esc(row.amazon_confidence)} · <a href="${esc(row.amazon_source_url)}" rel="noreferrer">evidence</a>`}</td><td>${row.collectr_usd==null||row.usd_mxn_rate==null?"⚠️ Missing":`US$${esc(row.collectr_usd)} @ ${esc(row.usd_mxn_rate)} · <a href="${esc(row.collectr_source_url)}" rel="noreferrer">exact variant</a>`}</td><td><details><summary>Update evidence</summary><form method="post" action="${action}"><fieldset><legend>Amazon México reference</legend><input name="amazon_launch_mxn" type="number" min="1" max="1000000" step="0.01" value="${esc(row.amazon_launch_mxn??"")}" placeholder="MXN"><select name="amazon_confidence"><option value="">Unchanged / none</option>${["exact","strong_proxy","estimated_range"].map(value=>`<option value="${value}"${row.amazon_confidence===value?" selected":""}>${value}</option>`).join("")}</select><input name="amazon_source_url" type="url" value="${esc(row.amazon_source_url??"")}" placeholder="https://www.amazon.com.mx/…"><input name="amazon_captured_at" type="datetime-local" value="${esc(localTime(row.amazon_captured_at))}"></fieldset><fieldset><legend>Collectr exact variant</legend><input name="collectr_usd" type="number" min="0.01" max="100000" step="0.01" value="${esc(row.collectr_usd??"")}" placeholder="USD"><input name="collectr_source_url" type="url" value="${esc(row.collectr_source_url??"")}" placeholder="https://www.collectr.com/…"><input name="collectr_captured_at" type="datetime-local" value="${esc(localTime(row.collectr_captured_at))}"><input name="usd_mxn_rate" type="number" min="1" max="100" step="0.0001" value="${esc(row.usd_mxn_rate??"")}" placeholder="USD/MXN"></fieldset><input name="reason" maxlength="500" required placeholder="Evidence and variant-match rationale"><button type="submit">Save pricing evidence</button></form></details></td></tr>`;}).join("");
  const pricingSection=`<section><h2>Pricing-reference coverage</h2><p>Amazon launch: <b>${amazonReferenceCount}/${pricing.length}</b> · Collectr exact variant: <b>${collectrReferenceCount}/${pricing.length}</b>. Missing references remain unavailable to customers; availability scans never invent or overwrite them.</p><div class="table"><table><thead><tr><th>Canonical product</th><th>Mapped offers</th><th>Amazon launch</th><th>Collectr</th><th>Operator evidence</th></tr></thead><tbody>${pricingRows}</tbody></table></div></section>`;
  const sections=[
    ["Spawn health",data.spawn],["Catch Em All health",data.catch_em_all??"CATCH_MONITOR_ENDPOINT not configured"],
    ["Seed campaigns",data.seed_campaigns],["Inventory revalidation",data.revalidation],["Removal reviews",data.removal_reviews],["Customer event ledger",data.customer_events],
    ["Vendor suppressions",data.vendors],["Discovery → ingestion",data.discovery_ingestion],["Weekly feedback trends",data.weekly_feedback]
  ];
  const queue=(data.verification_queue as Array<Record<string,unknown>>).map(row=>{
    const action=`/dashboard/verification/${esc(row.asin)}?access=${encodeURIComponent(token)}`;
    const hidden=`<input type="hidden" name="attempt_id" value="${esc(row.verification_attempt_id)}"><input type="hidden" name="evidence_revision" value="${esc(row.evidence_revision)}">`;
    return `<article><h3>${esc(row.product_name)}</h3><p><b>${esc(row.lifecycle_status)}</b> · ${esc(row.asin)} · queued ${esc(row.first_discovered_at)}</p><p>Admin request: <b>${esc(row.approval_notice_status??"not requested")}</b>${row.approval_notice_error?` · ${esc(row.approval_notice_error)}`:""}</p><p><a href="${esc(row.product_url)}" rel="noreferrer">Direct Amazon listing</a></p><details><summary>Latest independent verification</summary><pre>${esc(JSON.stringify({completed_at:row.verification_completed_at,outcome:row.verification_outcome,access:row.access_outcome,http:row.http_status,canonical_product_id:row.canonical_product_id,availability:row.observed_availability,confidence:row.confidence,gates:row.gate_results_json,unresolved:row.unresolved_questions},null,2))}</pre></details>
      <form method="post" action="${action}"><button name="action" value="verify">Run fresh verification</button></form>
      ${row.verification_attempt_id?`<form method="post" action="${action}">${hidden}<label>Reason <input name="reason" maxlength="500" required></label><label>Lane <select name="lane"><option value="normal">normal</option><option value="priority">priority</option></select></label><label>Route <select name="routing_key"><option>pokemon-main</option><option>pokemon-30th</option><option>delta-reign</option><option>magic-hobbit</option></select></label><label><input type="checkbox" name="alert_on_initial_buyable"> Alert on initial buyable</label><button name="action" value="approve">Approve</button><button name="action" value="reject">Reject</button>${row.lifecycle_status==="APPROVED"?`<button name="action" value="publish">Publish to Catch</button>`:""}</form>`:""}
      <details><summary>Decision history</summary><pre>${esc(row.decision_history)}</pre></details></article>`;
  }).join("")||"<p>No candidates awaiting review.</p>";
  const listingQueue=(data.listing_queue as Array<Record<string,unknown>>).map(row=>{const action=`/dashboard/listing/${esc(row.candidate_id)}?access=${encodeURIComponent(token)}`;return `<article><h3>${esc(row.product_name)}</h3><p><b>${esc(row.vendor)}</b> · ${esc(row.product_family)} · ${esc(row.language)}</p><p><b>Catch status: Not tracked — awaiting approval.</b></p><p>Observed: ${esc(row.availability_state)} · ${row.observed_price_mxn==null?"price unconfirmed":`MX$${esc(row.observed_price_mxn)}`} · ${esc(row.discovered_at)}</p><p>Admin alert: <b>${esc(row.notification_status??"not queued")}</b>${row.notification_error?` · ${esc(row.notification_error)}`:""}</p><p><a href="${esc(row.source_url)}" rel="noreferrer">Direct listing</a></p><form method="post" action="${action}"><input type="hidden" name="action" value="publish"><label>Publication <select name="disposition"><option value="visibility_only">Customer visibility only (no Catch monitoring)</option><option value="hourly">Publish + hourly Amazon monitoring</option><option value="five_minute">Publish + approved fast Amazon monitoring</option></select></label><label>Approval reason <input name="reason" maxlength="500" placeholder="Required: why this listing is approved" required></label><button type="submit">Approve and publish</button></form><form method="post" action="${action}" class="reject"><input type="hidden" name="action" value="reject"><label>Rejection reason <input name="reason" maxlength="500" placeholder="Required: why this listing is rejected" required></label><button type="submit">Reject</button></form></article>`;}).join("")||"<p>No new listings awaiting publication review.</p>";
  const message=feedback?.error?`<p class="message error"><b>Action failed:</b> ${esc(feedback.error)}</p>`:feedback?.notice?`<p class="message success"><b>Action completed:</b> ${esc(feedback.notice)}</p>`:"";
  return `<!doctype html><meta name="viewport" content="width=device-width"><title>Garfield operations</title><style>body{font:15px system-ui;background:#101114;color:#eef1e8;max-width:76rem;margin:auto;padding:2rem}header{display:flex;justify-content:space-between;align-items:end}a{color:#c9f65a}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}section,article{background:#191c17;border:1px solid #30352b;border-radius:14px;padding:1rem;overflow:auto}article{margin:.75rem 0;background:#131510}form{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center;margin:.7rem 0;padding:.6rem;border-left:3px solid #60703d}.reject{border-left-color:#8b3d3d}button,input,select{font:inherit;padding:.55rem}.message{padding:.8rem;border-radius:8px}.success{background:#23451e}.error{background:#5a2020}pre{white-space:pre-wrap;color:#bdc5b3}.table{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:.55rem;border-bottom:1px solid #30352b;white-space:nowrap}@media(max-width:700px){.grid{grid-template-columns:1fr}}</style><header><div><p>Project Garfield</p><h1>Operations dashboard</h1><p>Operator approval queue · Amazon catalog ${esc((data.catalog_version as {value?:string}|null)?.value??"0")} · Listing feed ${esc((data.publication_version as {value?:string}|null)?.value??"0")}</p></div><p><a href="/inventory?access=${encodeURIComponent(token)}">Inventory</a> · <a href="/inventory.csv?access=${encodeURIComponent(token)}">CSV</a></p></header>${message}${coverageSection}${pricingSection}<section><h2>New listing publication queue</h2><p>Items below are discovery evidence only and are not tracked by Catch until an Amazon monitoring disposition is approved and published.</p>${listingQueue}</section><section><h2>Amazon verification queue</h2><p>Verification records evidence only. Approval and publication are separate operator decisions.</p>${queue}</section><main class="grid">${sections.map(([title,value])=>`<section><h2>${esc(title)}</h2><pre>${esc(JSON.stringify(value,null,2))}</pre></section>`).join("")}</main>`;
}
