import {PRODUCT_LANGUAGES,languageLabel} from './contracts/amazon-catalog.mjs';
const esc=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]!);
export function productApprovalCard(row:Record<string,unknown>,token:string){
  let evidence:Record<string,unknown>={};try{evidence=JSON.parse(String(row.evidence_json||'{}'));}catch{}
  const input=(name:string,label:string,value:unknown,required=false)=>`<label>${label}<input name="${name}" value="${esc(value)}" maxlength="500"${required?' required':''}><span data-error-for="${name}" role="alert"></span></label>`;
  const alreadyPublished=row.listing_status==='ACCEPTED';
  return `<article class="approval-card"><h3>${esc(row.product_name)}</h3><p>${esc(row.asin)} · ${esc(languageLabel(String(row.language||'unknown')))} · ${alreadyPublished?'Already in inventory':'Awaiting approval'}</p>
    <p><a href="${esc(row.product_url)}" target="_blank" rel="noreferrer">Open Amazon listing ↗</a> · This listing is the supporting evidence.</p>
    <form class="approval-form" data-product-action method="post" action="/dashboard/verification/${esc(row.asin)}?access=${encodeURIComponent(token)}">
      <input type="hidden" name="action" value="approve_product"><input type="hidden" name="evidence_revision" value="${esc(row.evidence_revision)}">
      <div class="form-grid">${input('product_name','Product name',row.product_name,true)}${input('set_name','Set',evidence.set??row.print_series??'')}${input('format','Sealed format',evidence.format??row.product_type??'')}
      <label>Card language<select name="language">${PRODUCT_LANGUAGES.map(language=>`<option value="${language}"${language===(row.language||'unknown')?' selected':''}>${languageLabel(language)}</option>`).join('')}</select><span data-error-for="language" role="alert"></span></label></div>
      <p class="hint">Confirm the product details. Unknown language is allowed and shown explicitly. Missing or expired page verification refreshes when you approve.</p>
      <label>Publish to<select name="destination"><option value="visibility_only">Inventory only</option><option value="monitor"${alreadyPublished?' selected':''}>Inventory + Catch monitoring</option></select></label>
      ${alreadyPublished?'':`<details${row.fulfilment_region_state==='DOMESTIC'?'':' open'}><summary>Delivery to Mexico</summary><p>Confirm where the item ships from. The Amazon México URL alone does not establish delivery.</p><label>Delivery<select name="fulfilment_region_state" data-product-delivery><option value="CROSS_BORDER_UNVERIFIED">Needs confirmation</option><option value="DOMESTIC"${row.fulfilment_region_state==='DOMESTIC'?' selected':''}>Ships within Mexico</option><option value="CROSS_BORDER_CONFIRMED"${row.fulfilment_region_state==='CROSS_BORDER_CONFIRMED'?' selected':''}>International — delivery to Mexico confirmed</option></select></label><div class="form-grid" data-product-delivery-fields>${input('retailer_country','Retailer country (two letters)',row.retailer_country??'MX')}${input('ship_from_country','Ships from (two letters)',row.ship_from_country??'')}<label>Item price (international)<input name="original_price" type="number" min="0" step="0.01" value="${esc(row.original_price)}"></label>${input('original_currency','Currency (international)',row.original_currency??'')}<label>Delivery checked (UTC, international)<input name="destination_checked_at" type="datetime-local" value="${esc(String(row.destination_checked_at??'').slice(0,16))}"></label><label>Evidence valid until (UTC, international)<input name="destination_fresh_until" type="datetime-local" value="${esc(String(row.destination_fresh_until??'').slice(0,16))}"></label></div></details>`}
      <details><summary>Advanced monitoring settings and optional note</summary><div class="form-grid"><label>Requested cadence<select name="cadence"><option value="60">Hourly</option><option value="5">Every five minutes</option></select></label><label>Priority<select name="lane"><option value="normal">Normal</option><option value="priority">Priority</option></select></label><label><input type="checkbox" name="alert_on_initial_buyable">Alert if initially buyable</label>${input('reason','Optional approval note','')}</div><p class="hint">Route follows the product category. Catch applies its monitoring budget.</p></details>
      <p data-product-feedback role="status"></p><button type="submit" class="approve">Approve product</button>
    </form><details><summary>Verification and decision history</summary><pre>${esc(JSON.stringify({checked_at:row.verification_completed_at,outcome:row.verification_outcome,unresolved:row.unresolved_questions,history:row.decision_history},null,2))}</pre></details>
    <details><summary>Reject product</summary><form method="post" action="/dashboard/verification/${esc(row.asin)}?access=${encodeURIComponent(token)}"><input type="hidden" name="expected_state" value="${esc(row.lifecycle_status)}"><input type="hidden" name="attempt_id" value="${esc(row.verification_attempt_id)}"><input type="hidden" name="evidence_revision" value="${esc(row.evidence_revision)}"><input name="reason" required placeholder="Rejection reason"><button name="action" value="reject">Reject</button></form></details></article>`;
}

export const productApprovalScript=`for(const form of document.querySelectorAll('[data-product-action]')){const delivery=form.querySelector('[data-product-delivery]'),fields=form.querySelector('[data-product-delivery-fields]');if(delivery&&fields){const sync=()=>{fields.hidden=delivery.value!=='CROSS_BORDER_CONFIRMED';if(delivery.value==='DOMESTIC'){form.elements.retailer_country.value='MX';form.elements.ship_from_country.value='MX';}};delivery.addEventListener('change',sync);sync();}}for(const form of document.querySelectorAll('[data-product-action]'))form.addEventListener('submit',async event=>{event.preventDefault();const button=form.querySelector('button[type=submit]'),feedback=form.querySelector('[data-product-feedback]');button.disabled=true;feedback.textContent='Checking evidence and publishing…';for(const field of form.querySelectorAll('[data-error-for]'))field.textContent='';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{accept:'application/json'}});const result=await response.json();if(result.evidenceRevision)form.elements.evidence_revision.value=result.evidenceRevision;feedback.textContent=result.message||result.error||'Could not complete approval. Please retry.';for(const [key,message] of Object.entries(result.fields||{})){const field=form.querySelector('[data-error-for="'+key+'"]');if(field)field.textContent=message;}if(result.ok){button.textContent='Approved';form.dataset.completed='true';}}catch{feedback.textContent='Could not confirm the result. Your entries are preserved. Retry to check and finish approval.';}finally{button.disabled=form.dataset.completed==='true';}});`;
